### ISSUE TITLE
Triggers not recognised for Xbox one controller + Xbox Wireless Adapter 

### ISSUE THREAD

**Issue by TobyKLight** [heavy-d/VL.GameController#2]
## Issue
I have an Xbox controller connected via an Xbox Wireless Adapter.
Trigger Left and right are instead both appearing on the X axis of controller 1.
Which means they are taking the default axis, a0. 

## Workaround
Change the fallback controller profile to add LeftTrigger and RightTrigger on axis 2 and 5 respectively. 
`lefttrigger:a2`
`righttrigger:a5`

To do that 
* go to VL.GameController definition 
* go to process MatchSDLMapping
* replace the fallback string definition with 

`03000000c6240000fdfa000000000000,Fallback Controller,a:b0,b:b1,back:b6,dpdown:h0.4,dpleft:h0.8,dpright:h0.2,dpup:h0.1,leftshoulder:b4,leftstick:b8,leftx:a0,lefty:a1,lefttrigger:a2,rightshoulder:b5,rightstick:b9,rightx:a3,righty:a4,righttrigger:a5,start:b7,x:b2,y:b3,platform:Windows,`

Could this be a permanent solution? Or is there some reason fallback controller omits these?

Ideal solution would be to get the xbox controller detected properly but that may not be possible with the way stride reports the IDs, see below. 

## Background 

These controllers are not recognised from the SDL list, they appear as 'Fallback Controller [XInput Controller #1]' 

Looks like this 
![image](https://user-images.githubusercontent.com/4467208/226373457-37d423bc-4d0e-4435-aff7-a3e6ded96017.png)

They are recognised properly by https://gamepad-tester.com/ 
![image](https://user-images.githubusercontent.com/4467208/226374616-80003bb5-de31-4e42-bfb5-27f4235065e6.png)

Looking into the SDL list it seems these pads are a special case that should report a GUID of 'XInput', which of course isn't a GUID and not what stride reports. I guess the actual SDL library has some way of detecting this.
 

![image](https://user-images.githubusercontent.com/4467208/226374430-cc9f85c6-e9f6-4f04-93cb-edef4a7ed43d.png)

**Comment by heavy-d** [comment]
Great reporting, thx!
This Stride issue might be related:
https://github.com/stride3d/stride/issues/1333

>Could this be a permanent solution? Or is there some reason fallback controller omits these?

I didn't have a controller that registers as Fallback Controller, so there was no intention to omit the triggers.
So this looks like a good solution.
