### ISSUE TITLE
Two controllers of same type not recognised

### ISSUE THREAD

**Issue by TobyKLight** [heavy-d/VL.GameController#3]
## Issue

I have two Xbox controllers both connected via an Xbox Wireless Adapter.
Only one at a time is working. 

It seems to be because of this Distinct region in the GameControllerProcess. 
For my case at least the ProductID is the same for controllers of the same type. 
![image](https://user-images.githubusercontent.com/4467208/226380179-f961cfdc-4b4e-494d-9d9c-9aab319a75d9.png)

## Workaround
Disable the distinct region in an IF region 

![image](https://user-images.githubusercontent.com/4467208/226380565-2216bef0-40d5-4aa0-a73b-37816bd737f4.png)

I assume that Distinct region is there to handle some particular case. 
Could it be optional? Or another way to handle the issue that region is meant to solve?

**Comment by heavy-d** [comment]
I merged your commit, thanks for helping out!

The distinct region may be a relict from an earlier state, but not really sure.
